### PR TITLE
Translation to pt_br

### PR DESCRIPTION
**Pull request by Gleidson2012**
Translation of Chapter 1. Installing PHPUnit for pt_br (4.5/pt_br/installation.xml).

### CODE REVIEW

**Comment by Gleidson2012** [comment]
Sebastian.
When a language is added to the site?

**Comment by sebastianbergmann** [comment]
When it is complete and not outdated.

**Comment by Gleidson2012** [comment]
Right!
Version 4.6 will be how long?

**Comment by Gleidson2012** [comment]
Sorry!
[found it!](https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-4.6.0)

**Pull request merged**
