### PR TITLE
in a different way

### PR DESCRIPTION
**Pull request by franzholz**
wrong: "it is used a fundamentally different way"

http://www.linguee.de/englisch-deutsch/uebersetzung/in+a+different+way.html

### CODE REVIEW

**Comment by whatthejeff** [comment]
I think that is a [quote](http://xunitpatterns.com/Test%20Double.html#Mock%20Object) from Gerard Meszaros. There's actually an article missing earlier in the same sentence: 

> Therefore, a mock object **is lot more** than just a test stub plus assertions; it is used a fundamentally different way

**Comment by franzholz** [comment]
Yes, there is also an article missing. I think that this should be fixed. I do not think that the author wants  his misspellings to be kept.

**Comment by whatthejeff** [comment]
@sebastianbergmann mentioned using *`[sic]`* in a previous issue (#233).

**Comment by sebastianbergmann** [comment]
What do you think, @gmkayaker?

**Comment by gmkayaker** [comment]
Agreed. It should read: "Therefore, a mock object is *a* lot more than just a test stub plus assertions; it is used *in* a fundamentally different way."

Where is this quote from? Just so I can hunt it down and fix it at the source.

Thanks,

Gerard

**Comment by sebastianbergmann** [comment]
The quote is from http://xunitpatterns.com/Test%20Double.html#Mock%20Object IIRC.

**Comment by sebastianbergmann** [comment]
Merged manually, thanks.

**Pull request closed without merging**
