### PR TITLE
Added example for testsuite

### PR DESCRIPTION
**Pull request by fireproofsocks**
Resolves issue https://github.com/sebastianbergmann/phpunit-documentation/issues/327

Please consider https://github.com/sebastianbergmann/phpunit-documentation/issues/328

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
As of right now, new content needs to be added to `4.8`, `5.0`, `5.1`, and `5.2`. If it is applicable to all, of course.

**Comment by fireproofsocks** [comment]
Ok, I've updated docs for 4.8, 5.0, 5.1, and 5.2

**Comment by fireproofsocks** [comment]
This also includes a CONTRIBUTING.md file.

**Comment by sebastianbergmann** [comment]
Thank you for your contribution. I appreciate the time you invested in preparing this pull request. However, I have decided not to merge it.

**Pull request closed without merging**
