### PR TITLE
Adding documentation for @ticket functionality

### LINKED ISSUE #314: Update documentation for @ticket and @testdox annotations
https://phpunit.de/manual/current/en/appendixes.annotations.html#appendixes.annotations.testdox
https://phpunit.de/manual/current/en/appendixes.annotations.html#appendixes.annotations.ticket

These annotations don't have any documentation for what they do, how to use them etc.

### PR DESCRIPTION
**Pull request by Robotic-Brain**
Partially fixes #314

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
I am reluctant to add documentation for a feature that has been removed from PHPUnit 6.

https://github.com/sebastianbergmann/phpunit/commit/c9f8fe11fb459e51d37fcf629e0450307b19c362

**Comment by Robotic-Brain** [comment]
Well, it's part of phpunit 5, so it should be documented there, even if it's marked as "experimental"

However it might be better to rewrite it in terms of the basic PHPUnit_Framework_TestListener and document the PHPUnit_Util_Test::parseTestMethodAnnotations method instead.
e.g.: in a Section called "Implementing custom annotations"

In general I think there's an API appendix missing in the docs.
(even an auto-generated one would be great)

Off-Topic: what about @testdox ?

**Comment by alnutile** [comment]
Just wondering if this patch should be applied to the docs? https://phpunit.de/manual/current/en/appendixes.annotations.html#appendixes.annotations.ticket
Still empty there  
img_0219

**Comment by sebastianbergmann** [comment]
Thank you for your contribution. I appreciate the time you invested in preparing this pull request. However, I have decided not to merge it.

**Pull request closed without merging**
